# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    run_tests(scheme: "MyResumeTests")
  end


  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(app_identifier: "com.arthurkleiber", type: "appstore", readonly: true)
    build_app(workspace: "MyResume.xcworkspace", scheme: "MyResume")
    run_tests(scheme: "MyResumeTests")
    upload_to_testflight
  end
end
