# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [release]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gem Install
        run: gem install bundler:1.17.2
      - name: Bundle Install
        run: bundle install
      - name: Install cocoapods
        run: gem install cocoapods
      - name: Install pods
        run: pod install
      - name: Run Unit tests
        run: bundle exec fastlane tests
